// All 114 surahs with Arabic names, Dutch names, ayah counts, and primary juz
export interface Surah {
  nr: number;
  naam: string;       // Dutch/transliteration name
  naamAr: string;     // Arabic name
  ayaat: number;      // Total ayaat
  juz: number;        // Primary juz (1–30)
}

export const SURAHS: Surah[] = [
  { nr: 1, naam: "Al-Fatiha", naamAr: "الفاتحة", ayaat: 7, juz: 1 },
  { nr: 2, naam: "Al-Baqara", naamAr: "البقرة", ayaat: 286, juz: 1 },
  { nr: 3, naam: "Al-Imran", naamAr: "آل عمران", ayaat: 200, juz: 3 },
  { nr: 4, naam: "An-Nisa", naamAr: "النساء", ayaat: 176, juz: 4 },
  { nr: 5, naam: "Al-Ma'ida", naamAr: "المائدة", ayaat: 120, juz: 6 },
  { nr: 6, naam: "Al-An'am", naamAr: "الأنعام", ayaat: 165, juz: 7 },
  { nr: 7, naam: "Al-A'raf", naamAr: "الأعراف", ayaat: 206, juz: 8 },
  { nr: 8, naam: "Al-Anfal", naamAr: "الأنفال", ayaat: 75, juz: 9 },
  { nr: 9, naam: "At-Tawba", naamAr: "التوبة", ayaat: 129, juz: 10 },
  { nr: 10, naam: "Yunus", naamAr: "يونس", ayaat: 109, juz: 11 },
  { nr: 11, naam: "Hud", naamAr: "هود", ayaat: 123, juz: 11 },
  { nr: 12, naam: "Yusuf", naamAr: "يوسف", ayaat: 111, juz: 12 },
  { nr: 13, naam: "Ar-Ra'd", naamAr: "الرعد", ayaat: 43, juz: 13 },
  { nr: 14, naam: "Ibrahim", naamAr: "إبراهيم", ayaat: 52, juz: 13 },
  { nr: 15, naam: "Al-Hijr", naamAr: "الحجر", ayaat: 99, juz: 14 },
  { nr: 16, naam: "An-Nahl", naamAr: "النحل", ayaat: 128, juz: 14 },
  { nr: 17, naam: "Al-Isra", naamAr: "الإسراء", ayaat: 111, juz: 15 },
  { nr: 18, naam: "Al-Kahf", naamAr: "الكهف", ayaat: 110, juz: 15 },
  { nr: 19, naam: "Maryam", naamAr: "مريم", ayaat: 98, juz: 16 },
  { nr: 20, naam: "Ta-Ha", naamAr: "طه", ayaat: 135, juz: 16 },
  { nr: 21, naam: "Al-Anbiya", naamAr: "الأنبياء", ayaat: 112, juz: 17 },
  { nr: 22, naam: "Al-Hajj", naamAr: "الحج", ayaat: 78, juz: 17 },
  { nr: 23, naam: "Al-Mu'minun", naamAr: "المؤمنون", ayaat: 118, juz: 18 },
  { nr: 24, naam: "An-Nur", naamAr: "النور", ayaat: 64, juz: 18 },
  { nr: 25, naam: "Al-Furqan", naamAr: "الفرقان", ayaat: 77, juz: 18 },
  { nr: 26, naam: "Ash-Shu'ara", naamAr: "الشعراء", ayaat: 227, juz: 19 },
  { nr: 27, naam: "An-Naml", naamAr: "النمل", ayaat: 93, juz: 19 },
  { nr: 28, naam: "Al-Qasas", naamAr: "القصص", ayaat: 88, juz: 20 },
  { nr: 29, naam: "Al-'Ankabut", naamAr: "العنكبوت", ayaat: 69, juz: 20 },
  { nr: 30, naam: "Ar-Rum", naamAr: "الروم", ayaat: 60, juz: 21 },
  { nr: 31, naam: "Luqman", naamAr: "لقمان", ayaat: 34, juz: 21 },
  { nr: 32, naam: "As-Sajda", naamAr: "السجدة", ayaat: 30, juz: 21 },
  { nr: 33, naam: "Al-Ahzab", naamAr: "الأحزاب", ayaat: 73, juz: 21 },
  { nr: 34, naam: "Saba", naamAr: "سبأ", ayaat: 54, juz: 22 },
  { nr: 35, naam: "Fatir", naamAr: "فاطر", ayaat: 45, juz: 22 },
  { nr: 36, naam: "Ya-Sin", naamAr: "يس", ayaat: 83, juz: 22 },
  { nr: 37, naam: "As-Saffat", naamAr: "الصافات", ayaat: 182, juz: 23 },
  { nr: 38, naam: "Sad", naamAr: "ص", ayaat: 88, juz: 23 },
  { nr: 39, naam: "Az-Zumar", naamAr: "الزمر", ayaat: 75, juz: 23 },
  { nr: 40, naam: "Ghafir", naamAr: "غافر", ayaat: 85, juz: 24 },
  { nr: 41, naam: "Fussilat", naamAr: "فصلت", ayaat: 54, juz: 24 },
  { nr: 42, naam: "Ash-Shura", naamAr: "الشورى", ayaat: 53, juz: 25 },
  { nr: 43, naam: "Az-Zukhruf", naamAr: "الزخرف", ayaat: 89, juz: 25 },
  { nr: 44, naam: "Ad-Dukhan", naamAr: "الدخان", ayaat: 59, juz: 25 },
  { nr: 45, naam: "Al-Jathiya", naamAr: "الجاثية", ayaat: 37, juz: 25 },
  { nr: 46, naam: "Al-Ahqaf", naamAr: "الأحقاف", ayaat: 35, juz: 26 },
  { nr: 47, naam: "Muhammad", naamAr: "محمد", ayaat: 38, juz: 26 },
  { nr: 48, naam: "Al-Fath", naamAr: "الفتح", ayaat: 29, juz: 26 },
  { nr: 49, naam: "Al-Hujurat", naamAr: "الحجرات", ayaat: 18, juz: 26 },
  { nr: 50, naam: "Qaf", naamAr: "ق", ayaat: 45, juz: 26 },
  { nr: 51, naam: "Adh-Dhariyat", naamAr: "الذاريات", ayaat: 60, juz: 26 },
  { nr: 52, naam: "At-Tur", naamAr: "الطور", ayaat: 49, juz: 27 },
  { nr: 53, naam: "An-Najm", naamAr: "النجم", ayaat: 62, juz: 27 },
  { nr: 54, naam: "Al-Qamar", naamAr: "القمر", ayaat: 55, juz: 27 },
  { nr: 55, naam: "Ar-Rahman", naamAr: "الرحمن", ayaat: 78, juz: 27 },
  { nr: 56, naam: "Al-Waqi'a", naamAr: "الواقعة", ayaat: 96, juz: 27 },
  { nr: 57, naam: "Al-Hadid", naamAr: "الحديد", ayaat: 29, juz: 27 },
  { nr: 58, naam: "Al-Mujadila", naamAr: "المجادلة", ayaat: 22, juz: 28 },
  { nr: 59, naam: "Al-Hashr", naamAr: "الحشر", ayaat: 24, juz: 28 },
  { nr: 60, naam: "Al-Mumtahina", naamAr: "الممتحنة", ayaat: 13, juz: 28 },
  { nr: 61, naam: "As-Saf", naamAr: "الصف", ayaat: 14, juz: 28 },
  { nr: 62, naam: "Al-Jumu'a", naamAr: "الجمعة", ayaat: 11, juz: 28 },
  { nr: 63, naam: "Al-Munafiqun", naamAr: "المنافقون", ayaat: 11, juz: 28 },
  { nr: 64, naam: "At-Taghabun", naamAr: "التغابن", ayaat: 18, juz: 28 },
  { nr: 65, naam: "At-Talaq", naamAr: "الطلاق", ayaat: 12, juz: 28 },
  { nr: 66, naam: "At-Tahrim", naamAr: "التحريم", ayaat: 12, juz: 28 },
  { nr: 67, naam: "Al-Mulk", naamAr: "الملك", ayaat: 30, juz: 29 },
  { nr: 68, naam: "Al-Qalam", naamAr: "القلم", ayaat: 52, juz: 29 },
  { nr: 69, naam: "Al-Haqqa", naamAr: "الحاقة", ayaat: 52, juz: 29 },
  { nr: 70, naam: "Al-Ma'arij", naamAr: "المعارج", ayaat: 44, juz: 29 },
  { nr: 71, naam: "Nuh", naamAr: "نوح", ayaat: 28, juz: 29 },
  { nr: 72, naam: "Al-Jinn", naamAr: "الجن", ayaat: 28, juz: 29 },
  { nr: 73, naam: "Al-Muzzammil", naamAr: "المزمل", ayaat: 20, juz: 29 },
  { nr: 74, naam: "Al-Muddaththir", naamAr: "المدثر", ayaat: 56, juz: 29 },
  { nr: 75, naam: "Al-Qiyama", naamAr: "القيامة", ayaat: 40, juz: 29 },
  { nr: 76, naam: "Al-Insan", naamAr: "الإنسان", ayaat: 31, juz: 29 },
  { nr: 77, naam: "Al-Mursalat", naamAr: "المرسلات", ayaat: 50, juz: 29 },
  { nr: 78, naam: "An-Naba", naamAr: "النبأ", ayaat: 40, juz: 30 },
  { nr: 79, naam: "An-Nazi'at", naamAr: "النازعات", ayaat: 46, juz: 30 },
  { nr: 80, naam: "'Abasa", naamAr: "عبس", ayaat: 42, juz: 30 },
  { nr: 81, naam: "At-Takwir", naamAr: "التكوير", ayaat: 29, juz: 30 },
  { nr: 82, naam: "Al-Infitar", naamAr: "الانفطار", ayaat: 19, juz: 30 },
  { nr: 83, naam: "Al-Mutaffifin", naamAr: "المطففين", ayaat: 36, juz: 30 },
  { nr: 84, naam: "Al-Inshiqaq", naamAr: "الانشقاق", ayaat: 25, juz: 30 },
  { nr: 85, naam: "Al-Buruj", naamAr: "البروج", ayaat: 22, juz: 30 },
  { nr: 86, naam: "At-Tariq", naamAr: "الطارق", ayaat: 17, juz: 30 },
  { nr: 87, naam: "Al-A'la", naamAr: "الأعلى", ayaat: 19, juz: 30 },
  { nr: 88, naam: "Al-Ghashiya", naamAr: "الغاشية", ayaat: 26, juz: 30 },
  { nr: 89, naam: "Al-Fajr", naamAr: "الفجر", ayaat: 30, juz: 30 },
  { nr: 90, naam: "Al-Balad", naamAr: "البلد", ayaat: 20, juz: 30 },
  { nr: 91, naam: "Ash-Shams", naamAr: "الشمس", ayaat: 15, juz: 30 },
  { nr: 92, naam: "Al-Layl", naamAr: "الليل", ayaat: 21, juz: 30 },
  { nr: 93, naam: "Ad-Duha", naamAr: "الضحى", ayaat: 11, juz: 30 },
  { nr: 94, naam: "Ash-Sharh", naamAr: "الشرح", ayaat: 8, juz: 30 },
  { nr: 95, naam: "At-Tin", naamAr: "التين", ayaat: 8, juz: 30 },
  { nr: 96, naam: "Al-'Alaq", naamAr: "العلق", ayaat: 19, juz: 30 },
  { nr: 97, naam: "Al-Qadr", naamAr: "القدر", ayaat: 5, juz: 30 },
  { nr: 98, naam: "Al-Bayyina", naamAr: "البينة", ayaat: 8, juz: 30 },
  { nr: 99, naam: "Az-Zalzala", naamAr: "الزلزلة", ayaat: 8, juz: 30 },
  { nr: 100, naam: "Al-'Adiyat", naamAr: "العاديات", ayaat: 11, juz: 30 },
  { nr: 101, naam: "Al-Qari'a", naamAr: "القارعة", ayaat: 11, juz: 30 },
  { nr: 102, naam: "At-Takathur", naamAr: "التكاثر", ayaat: 8, juz: 30 },
  { nr: 103, naam: "Al-'Asr", naamAr: "العصر", ayaat: 3, juz: 30 },
  { nr: 104, naam: "Al-Humaza", naamAr: "الهمزة", ayaat: 9, juz: 30 },
  { nr: 105, naam: "Al-Fil", naamAr: "الفيل", ayaat: 5, juz: 30 },
  { nr: 106, naam: "Quraysh", naamAr: "قريش", ayaat: 4, juz: 30 },
  { nr: 107, naam: "Al-Ma'un", naamAr: "الماعون", ayaat: 7, juz: 30 },
  { nr: 108, naam: "Al-Kawthar", naamAr: "الكوثر", ayaat: 3, juz: 30 },
  { nr: 109, naam: "Al-Kafirun", naamAr: "الكافرون", ayaat: 6, juz: 30 },
  { nr: 110, naam: "An-Nasr", naamAr: "النصر", ayaat: 3, juz: 30 },
  { nr: 111, naam: "Al-Masad", naamAr: "المسد", ayaat: 5, juz: 30 },
  { nr: 112, naam: "Al-Ikhlas", naamAr: "الإخلاص", ayaat: 4, juz: 30 },
  { nr: 113, naam: "Al-Falaq", naamAr: "الفلق", ayaat: 5, juz: 30 },
  { nr: 114, naam: "An-Nas", naamAr: "الناس", ayaat: 6, juz: 30 },
];

export function getSurah(nr: number): Surah | undefined {
  return SURAHS.find((s) => s.nr === nr);
}

/** Total ayaat from surah X ayah Y up to and including surah X2 ayah Y2 (same surah) */
export function ayaatInRange(surahNr: number, vanAyah: number, totAyah: number): number {
  return Math.max(0, totAyah - vanAyah + 1);
}

/** All surahs in juz 30 (common starting point) */
export const JUZ30 = SURAHS.filter((s) => s.juz === 30);
